# 配置文件

DAILY_TIME: "8:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-11-21" # 纪念日
CITY: "南京"

BIRTHDAY:
  - "0816"
APP_ID: "wx70429c1600b1e3d3"
APP_SECRET: "9c84c70fef78961bf4763d64ca067c35"

USER_ID: 
  - "o754G6Ij9kSY8cmTcD-Z6WAoRGQU"
TEMPLATE_ID: "U6ToevrSJr4i_HxtERnBcVhQgWcUEo2GwT-YUKF9HpI"
